### PR TITLE
Adding Movers which can accept more than 3 points, and others

### PR DESCRIPTION
**Pull request by Awlexus**
Improved my other movers, added a Sinus Mover and made a little optimization.

### CODE REVIEW

**Comment by yugecin** [comment]
notes: 
* I merged the polymovers into the existing mover list
* slidermovers are disabled for the polymovers

Thanks

**Comment by Awlexus** [comment]
The Poly-linearmover actually just calls the standard one. It won't be necessary in the future, since I've made a generic Factory and mover, which just need a class to function like the original.

**Comment by yugecin** [comment]
I see you're still adding thing but you haven't pulled in the meantime. I changed some important stuff inside the Dancer etc class.

**Comment by Awlexus** [comment]
I noticed that. I ran into some trouble while merging, so I will make a pull request once I've fixed it (again). This should also solve #79

**Pull request merged**
